### ISSUE TITLE
TOC gives erros

### ISSUE THREAD

**Issue by tyeeman** [jaredkrinke/md2blog#49]
Hi again. I'm running your unmodified (by me) version and I'm getting errors when the .md file has a TOC. Here is part of the TOC - 

```
<!-- TOC start -->
- [**Introduction - August 2022**](#introduction-august-2022)
- [**Upcoming SISKA Events**](#upcoming-siska-events)
- [**Upcoming NonSISKA Events**](#upcoming-nonsiska-events)
- [**Community Events of Interest**](#community-events-of-interest)
- [**Upcoming Courses**](#upcoming-courses)
- ```
Here is the error - 

```
md2blog --clean --serve
←[0m←[1m←[31merror←[0m: TypeError: Cannot read properties of undefined (reading 'split')
    at file://$deno$/bundle.js:7162:66
    at GoldsmithObject.run (file://$deno$/bundle.js:1457:28)
    at async GoldsmithObject.build (file://$deno$/bundle.js:1493:23)
    at async file://$deno$/bundle.js:55045:1
```
Anything come to mind?

**Comment by jaredkrinke** [comment]
Not sure why I didn't see this until now, but I'll take a look. That is probably a bug in my code...

**Comment by jaredkrinke** [comment]
Just for my own understanding, how are you creating the actual anchor tag?

I tested using a Markdown heading (e.g. `# Heading`), but I could only reproduce this error if I used inline HTML (e.g. `<a id="introduction-august-2022">test</a>`) -- there are probably more approaches that I haven't thought of, thus my question. Side note: `# Introduction - August 2022` produces an anchor with id `#introduction---august-2022`, in case you want to switch to using Markdown heading.
